import a18n from 'a18n';

export const TUIRoomErrorCode = {
  INVALID_PARAM_ERROR: -1000,
  LOGIN_ERROR: -1001,
  LOGOUT_ERROR: -1002,
  NOT_LOGIN: -1003,
  TIM_ERROR: -1004,
  TRTC_NOT_EXIST_ERROR: -1005,
  ROOM_EXISTED: -1006,
  SDK_NOT_READY: -1007,
  CREATE_GROUP_ERROR: -1008,
  JOIN_GROUP_ERROR: -1009,
  QUIT_GROUP_ERROR: -1010,
  DISMISS_GROUP_ERROR: -1011,
  SEND_MESSAGE_ERROR: -1012,
  SEND_CUSTOM_MESSAGE_ERROR: -1013,
  CREATE_ROOM_ERROR: -1014,
  DESTROY_ROOM_ERROR: -1015,
  ENTER_ROOM_ERROR: -1016,
  EXIT_ROOM_ERROR: -1017,
  SET_ROOM_CONTROL_CONFIG_ERROR: -1018,
  GROUP_NOT_EXIST_ERROR: -1019,
  CHANGE_ALL_MIC_MUTE_ERROR: -1020,
  ROOM_BEEN_DESTROYED: -1997,
  NO_PRIVILEGE: -1998,
  UNKNOWN_ERROR: -1999,

  CALLING_ROLL: -2000,
  NOT_CALL_ROLL: -2001,
  START_CALL_ROLL_ERROR: -2002,
  STOP_CALL_ROLL_ERROR: -2003,
  SEND_SPEECH_APPLICATION_EORRO: -2004,

  TS_INVITE_ERROR: -2010,
  TS_CMD_ERROR: -2011,
};

export const TUIRoomErrorMessage = {
  INVALID_PARAM_ERROR: a18n('无效参数'),
  LOGIN_ERROR: a18n('登录失败'),
  LOGOUT_ERROR: a18n('登出失败'),
  LOGOUT_TIM_ERROR: a18n('退出 TIM 失败'),
  LOGOUT_TRTC_ERROR: a18n('退出 TRTC 房间失败'),
  NOT_LOGIN: a18n('未登录'),
  TRTC_NOT_EXIST_ERROR: a18n('TRTC 实例未创建'),
  ROOM_EXISTED: a18n('房间已存在'),
  SDK_NOT_READY: a18n('SDK 初始化未完成'),
  CREATE_GROUP_ERROR: a18n('创建群组失败'),
  JOIN_GROUP_ERROR: a18n('加入群组失败'),
  QUIT_GROUP_ERROR: a18n('退出群组失败'),
  DISMISS_GROUP_ERROR: a18n('解散群组失败'),
  SEND_MESSAGE_ERROR: a18n('发送文本消息失败'),
  SEND_CUSTOM_MESSAGE_ERROR: a18n('发送自定义消息失败'),
  CREATE_ROOM_ERROR: a18n('创建房间失败'),
  DESTROY_ROOM_ERROR: a18n('销毁房间失败'),
  ENTER_ROOM_ERROR: a18n('进入房间失败'),
  EXIT_ROOM_ERROR: a18n('退出房间失败'),
  ROOM_BEEN_DESTROYED: a18n('房间实例已被销毁'),
  SET_ROOM_CONTROL_CONFIG_ERROR: a18n('设置房间控制配置失败'),
  GROUP_NOT_EXIST_ERROR: a18n('群组不存在'),
  CHANGE_ALL_MIC_MUTE_ERROR: a18n('修改全员禁麦克风状态失败'),
  NO_PRIVILEGE: a18n('无权限'),
  UNKNOWN_ERROR: a18n('未知错误'),

  CALLING_ROLL: a18n('正在点名中'),
  NOT_CALL_ROLL: a18n('尚未开始点名'),
  START_CALL_ROLL_ERROR: a18n('开始点名失败'),
  STOP_CALL_ROLL_ERROR: a18n('结束点名失败'),
  SEND_SPEECH_APPLICATION_EORRO: a18n('申请发言失败'),

  TS_INVITE_ERROR: a18n('邀请信令已在流程中，请不要重复邀请'),
  TS_CMD_ERROR: a18n('本次响应操作无对应邀请事件信令'),
};

export const CommonConstant = {
  groupIDPrefix: 'Room_',
};

export const TSignalingConfig = {
  timeout: 60,
};
